spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: 'create'
    properties:
      hibernate:
        dialect:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

#server:
#  port: 8123